<?php
/*
 * Copyright Extend (c) 2023. All rights reserved.
 * See Extend-COPYING.txt for license details.
 */

/** @var $block \Magento\Catalog\Block\Product\View */

$viewModel = $block->getData('viewModel');
$isCurrencySupported = $viewModel->isCurrencySupported();
$shouldRender = $viewModel->isExtendProductProtectionEnabled() && $viewModel->isProductProtectionProductDisplayPageOfferEnabled() && $isCurrencySupported;

if ($shouldRender) {
    $categoryModel = $block->getData('categoryModel');
    $product = $block->getProduct();
    $productSku = $product->getSku();
    $categoryName = '';
    $categories = $product->getAvailableInCategories();

    if (count($categories) > 0) {
        $categoryName = $categoryModel->getCategoryNameById($categories[count($categories) - 1]);
    }


    /** sanitizing to prevent whitespace and other abnormal characters from being used in a div id */
    $sanitizedProductSku = preg_replace('/[^a-zA-Z0-9-_|]/', '',  $productSku);
    $currencyCode = $viewModel->getCurrencyCode();
}

?>
<?php if ($shouldRender) : ?>
  <div class="product-protection-offer" id="product_protection_offer_<?= $sanitizedProductSku ?>"></div>
  <script type="text/x-magento-init">
    {
          "#product_protection_offer_<?= $sanitizedProductSku ?>": {
              "productProtectionOffer": [
                  {
                      "extendStoreUuid": "<?= $viewModel->getExtendStoreUuid() ?>",
                      "activeEnvironment": "<?= $viewModel->getActiveEnvironment() ?>",
                      "selectedProductSku": "<?= $productSku; ?>",
                      "selectedProductPrice": "<?= $product->getFinalPrice($block->getProductDefaultQty()); ?>",
                      "productCategory": "<?= $categoryName; ?>",
                      "currencyCode": "<?= $currencyCode ?>"
                  }
              ]
          }
      }
  </script>
<?php endif; ?>
